import { BikeConfig, TrackConfig } from './types';

export const BIKES: BikeConfig[] = [
  {
    id: 'bike_50cc',
    name: 'Interceptor GT',
    cc: 1600,
    description: 'Carro esportivo leve, turbo e ágil. Excelente controle em curvas fechadas com aríetes de impacto lateral reforçados.',
    topSpeed: 145, // km/h scaled
    acceleration: 48,
    handling: 85,
    durability: 90,
    weapon: 'FIST',
    weaponDamage: 20,
    weaponRange: 0.42,
    unlocked: true,
    cost: 0,
    color: '#eab308', // yellow
    accentColor: '#1e293b',
  },
  {
    id: 'bike_250cc',
    name: 'Iron Muscle 350',
    cc: 5700,
    description: 'Clássico V8 Muscle Car com chassi de aço pesado, aerofólio traseiro e para-choque de combate.',
    topSpeed: 180,
    acceleration: 64,
    handling: 72,
    durability: 125,
    weapon: 'BASEBALL_BAT',
    weaponDamage: 35,
    weaponRange: 0.46,
    unlocked: false,
    cost: 1400,
    color: '#ef4444', // red
    accentColor: '#0f172a',
  },
  {
    id: 'bike_500cc',
    name: 'Dune Marauder 4x4',
    cc: 4200,
    description: 'Monstro off-road de alto torque com tração integral, lâminas laterais retráteis e corrente de choque.',
    topSpeed: 210,
    acceleration: 78,
    handling: 68,
    durability: 150,
    weapon: 'CHAIN_WHIP',
    weaponDamage: 48,
    weaponRange: 0.54,
    unlocked: false,
    cost: 3200,
    color: '#f97316', // orange
    accentColor: '#451a03',
  },
  {
    id: 'bike_750cc',
    name: 'Neon Cyber Phantom',
    cc: 3800,
    description: 'Superesportivo estilo Neo-Tokyo com motor bi-turbo, aerodinâmica de efeito solo e esporões de titânio.',
    topSpeed: 242,
    acceleration: 90,
    handling: 80,
    durability: 135,
    weapon: 'LEAD_PIPE',
    weaponDamage: 44,
    weaponRange: 0.48,
    unlocked: false,
    cost: 6000,
    color: '#06b6d4', // cyan
    accentColor: '#1e1b4b',
  },
  {
    id: 'bike_1000cc',
    name: 'Thunder Titan V12',
    cc: 6500,
    description: 'O bólido supremo do campeonato mundial. V12 bi-turbo com labaredas duplas e aríetes de choque devastadores.',
    topSpeed: 280,
    acceleration: 98,
    handling: 85,
    durability: 175,
    weapon: 'SPIKED_MACE',
    weaponDamage: 65,
    weaponRange: 0.58,
    unlocked: false,
    cost: 9500,
    color: '#a855f7', // purple
    accentColor: '#172554',
  },
];

export const TRACKS: TrackConfig[] = [
  {
    id: 'track_usa',
    name: 'Red Rock Canyon',
    country: 'USA',
    city: 'Las Vegas',
    flag: '🇺🇸',
    distanceKm: 5.4,
    totalSegments: 600,
    laps: 2,
    skyColors: ['#fb923c', '#fdba74'], // sunset canyon
    horizonType: 'DESERT',
    roadColors: {
      grassLight: '#c2410c',
      grassDark: '#9a3412',
      rumbleLight: '#ffffff',
      rumbleDark: '#b91c1c',
      roadLight: '#475569',
      roadDark: '#334155',
      laneColor: '#facc15',
    },
    scenerySprites: ['CACTUS', 'ROCK', 'SIGN'],
    curveComplexity: 1.0,
    hillComplexity: 0.8,
    rivalCount: 7,
    unlocked: true,
  },
  {
    id: 'track_italy',
    name: 'Monaco Coastal Circuit',
    country: 'Italy',
    city: 'Monaco',
    flag: '🇮🇹',
    distanceKm: 6.8,
    totalSegments: 750,
    laps: 2,
    skyColors: ['#38bdf8', '#bae6fd'], // azure coastal sky
    horizonType: 'COAST',
    roadColors: {
      grassLight: '#15803d',
      grassDark: '#166534',
      rumbleLight: '#ffffff',
      rumbleDark: '#15803d',
      roadLight: '#334155',
      roadDark: '#1e293b',
      laneColor: '#ffffff',
    },
    scenerySprites: ['PALM', 'VILLA', 'SIGN'],
    curveComplexity: 1.5,
    hillComplexity: 1.2,
    rivalCount: 7,
    unlocked: true,
  },
  {
    id: 'track_japan',
    name: 'Tokyo Expressway',
    country: 'Japan',
    city: 'Tokyo',
    flag: '🇯🇵',
    distanceKm: 7.6,
    totalSegments: 850,
    laps: 2,
    skyColors: ['#312e81', '#1e1b4b'], // midnight neon
    horizonType: 'CITY_NIGHT',
    roadColors: {
      grassLight: '#1e1b4b',
      grassDark: '#0f172a',
      rumbleLight: '#ec4899',
      rumbleDark: '#06b6d4',
      roadLight: '#18181b',
      roadDark: '#09090b',
      laneColor: '#f43f5e',
    },
    scenerySprites: ['CHERRY_BLOSSOM', 'NEON_BILLBOARD', 'SIGN'],
    curveComplexity: 1.8,
    hillComplexity: 1.0,
    rivalCount: 7,
    unlocked: true,
  },
  {
    id: 'track_france',
    name: 'Alps Pass & Provencal',
    country: 'France',
    city: 'Alpes',
    flag: '🇫🇷',
    distanceKm: 8.5,
    totalSegments: 950,
    laps: 2,
    skyColors: ['#0284c7', '#7dd3fc'], // crisp alpine sky
    horizonType: 'ALPS',
    roadColors: {
      grassLight: '#65a30d',
      grassDark: '#4d7c0f',
      rumbleLight: '#ffffff',
      rumbleDark: '#1d4ed8',
      roadLight: '#3f3f46',
      roadDark: '#27272a',
      laneColor: '#ffffff',
    },
    scenerySprites: ['PINE', 'WINDMILL', 'ROCK'],
    curveComplexity: 2.0,
    hillComplexity: 2.2,
    rivalCount: 7,
    unlocked: true,
  },
  {
    id: 'track_brazil',
    name: 'Circuito Rio & Pão de Açúcar',
    country: 'Brasil',
    city: 'Rio de Janeiro',
    flag: '🇧🇷',
    distanceKm: 7.2,
    totalSegments: 800,
    laps: 2,
    skyColors: ['#065f46', '#f59e0b'], // golden sunset over emerald bay
    horizonType: 'TROPICAL_RIO',
    roadColors: {
      grassLight: '#16a34a',
      grassDark: '#15803d',
      rumbleLight: '#fde047', // Vibrant Brazilian yellow
      rumbleDark: '#16a34a',  // Brazilian green
      roadLight: '#334155',
      roadDark: '#1e293b',
      laneColor: '#fef08a',
    },
    scenerySprites: ['PALM', 'VILLA', 'SIGN'],
    curveComplexity: 0.75,
    hillComplexity: 0.4,
    rivalCount: 7,
    unlocked: true,
  },
];

export const RIVAL_NAMES = [
  'Viper Rex',
  'Axle Crash',
  'Raven',
  'Nitro Jones',
  'Spike Miller',
  'Scarlet',
  'Mad Dog',
  'Ghost',
  'Bone Crusher',
  'Blaze',
];

export const RIVAL_COLORS = [
  { bike: '#ef4444', suit: '#991b1b' },
  { bike: '#3b82f6', suit: '#1e3a8a' },
  { bike: '#10b981', suit: '#064e3b' },
  { bike: '#f59e0b', suit: '#78350f' },
  { bike: '#8b5cf6', suit: '#4c1d95' },
  { bike: '#ec4899', suit: '#831843' },
  { bike: '#14b8a6', suit: '#134e4a' },
  { bike: '#f43f5e', suit: '#881337' },
];
